swagger: '2.0'
info:
  title: Newspaper Backend API
  version: 1.0.0
paths:
  /lookup/{title}:
    parameters:
      - name: title
        in: path
        description: Title of the news article
        required: true
        type: string
    get:
      summary: Perform a news lookup by title
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              title:
                type: string
              news:
                type: string
    post:
      summary: Save a news article
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: title
          in: path
          description: Title of the news article
          required: true
          type: string
        - name: body
          in: body
          description: News article details
          required: true
          schema:
            type: object
            properties:
              news:
                type: string
      responses:
        '200':
          description: Successful operation
          schema:
            type: object
            properties:
              success:
                type: boolean
              message:
                type: string
  /login:
    get:
      summary: Login page
      responses:
        '200':
          description: Successful operation
          schema:
            type: string
